server:
  port: 8080
  servlet:
    context-path: /api

spring:
  #datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playground_v3?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: diboot
    password: diboot
    hikari:
      maximum-pool-size: 5
      max-lifetime: 60000 # 连接的最大生命周期

# Redis config
#  redis:
#    database: 0
#    port: 6379
#    host: localhost
#    password:

logging:
  level:
    root: debug
    org:
      apache: info
      hibernate:
        validator: info
      springframework: info
    _org:
      springframework: info
    com:
      diboot:
        lcdp: info
      zaxxer:
        hikari: info

# Diboot Configuration
diboot:
  init-sql: true #自动初始化SQL，开发环境下初次启动开启，初始化后可关闭
  file:
    # 文件存储路径（本地存储方式）
    storage-directory: D:/temp/playground
  iam:
    # token-expires-minutes: 60
    # Shiro的匿名urls
    anon-urls:
      - /swagger**/**
      - /webjars/**
      - /v3/**
      - /doc.html
      - /diboot-devtools/** # 允许devtools直接访问
  lcdp:
    #license: 订阅用户配置该项
    devtools:
      codes-author: MyName
      codes-copyright: MyCorp
      codes-version: 1.0
      output-path: demo/src/main/java/com/example/demo/
      output-path-admin-ui: diboot-admin-ui/